### ISSUE TITLE
SimpleITK Version?

### ISSUE THREAD

**Issue by 1vpmaster** [Noodles-321/Registration#1]
I try to use SimpleITK==2.02 or 1.24, but still has mistake.
Traceback (most recent call last):
  File "D:/lab_project/hand_match/experiment/registration_eval.py", line 20, in <module>
    img_rec, field = register_mi(img_src,img_tar,n_res=4)
  File "D:\lab_project\hand_match\utils\mi.py", line 28, in register_mi
    parameterMap = sitk.GetDefaultParameterMap('rigid')
AttributeError: module 'SimpleITK' has no attribute 'GetDefaultParameterMap'

**Comment by ludles** [comment]
To directly answer your question, I used `2.0.0rc2.dev908-g8244e`.

But I guess your error is related to the installation of [`SimpleElastix`](https://simpleelastix.readthedocs.io/GettingStarted.html). Please check if https://github.com/SuperElastix/SimpleElastix/issues/385 and https://github.com/SuperElastix/SimpleElastix/issues/323 can help.

**Comment by ludles** [comment]
I am closing this issue. But please feel free to re-open it if you have further questions.
